name: app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_bloc: ^8.1.6
  go_router: ^14.2.0
  equatable: ^2.0.5
  dio: ^5.4.3+1
  get_it: ^7.7.0
  flutter_gen_runner: ^5.6.0
  flutter_svg: ^2.0.10+1
  flutter_dotenv: ^5.1.0
  dartz: ^0.10.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/fonts/
    - assets/icons/
    - assets/images/
